name = "StatFiles"
uuid = "1463e38c-9381-5320-bcd4-4134955f093a"
version = "0.8.1-DEV"

[deps]
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
ReadStat = "d71aba96-b539-5138-91ee-935c3ee1374c"
TableShowUtils = "5e66a065-1f0a-5976-b372-e0b8c017ca10"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
DataValues = "0.4.4"
FileIO = "1"
IterableTables = "0.8.3, 0.9, 0.10, 0.11, 1"
IteratorInterfaceExtensions = "0.1.1, 1"
ReadStat = "0.4.1, 1"
TableShowUtils = "0.1.1, 0.2"
TableTraits = "0.3.1, 0.4, 1"
TableTraitsUtils = "0.2.1, 0.3, 0.4, 1"
julia = "1"
